### ISSUE TITLE
Some improvements on the Instruction set provided.

### ISSUE THREAD

**Issue by Ameya05** [airavata-courses/neeraj-lad#3]
Please mention details of the Python, Node, PHP, etc version requirement in the instruction steps.
While trying to run Flask app, I noticed that the python code is in 3.x and was failing on my installation of 2.x, so it would be better to have it mentioned in the instructions for ease of setup.

Also, MySQL workbench is an IDE / GUI for MySQL which is not recommended since going forward, deployment would be on servers with no UI. These servers would be accessible only from terminal/command line. 
I would suggest you to change the instructions of setting up a DB to a more detailed command specific instructions for setting it up in MySQL server. I have done that for now on my machine for reviewing the code.

**Comment by Ameya05** [comment]
Node commands should be using sudo.

And for me it worked like **nodejs** gateway.js instead of **node** gateway.js on my ubuntu 16.04 LTS.
Do check on the the reason for that and update the steps appropriately.

**Comment by Ameya05** [comment]
For PHP 7.0, the mysqli package is not included by default and had to install is separately. So I am guessing you tested this on a lower version of PHP.

Anyways, once u add the correct version of PHP in the instructions, this won't be a concern.

**Comment by neeraj-lad** [comment]
Thank you for the inputs @Ameya05! I'll make the necessary changes.

**Comment by neeraj-lad** [comment]
I have incorporated your suggestions in the wiki. If it looks good to you, then let's close this issue.

**Comment by Ameya05** [comment]
looks good to me.
