### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by nikchett** [airavata-courses/neeraj-lad#9]
pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

Hi Neeraj,

Followed the steps mentioned in the wiki of your repo and getting the mentioned above. 

Please suggest the steps to change it for easier future installations.

**Comment by neeraj-lad** [comment]
Hi @nikchett, `feature-addMsgBroker` is the branch with the latest commit. You can try running the steps on that branch. I will merge it with `asgn-2` once I have fully integrated the message broker.

**Comment by neeraj-lad** [comment]
Make sure that you do `git pull origin <branch_name>` before testing to pull the latest changes from any branch, since I am continuously pushing updates to the remote.

**Comment by neeraj-lad** [comment]
I have completed the message broker feature. You can test it by pulling the latest changes from `asgn-2`.
